version: '3.9'

services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - storage

volumes:
    postgres_data:

networks:
    storage:
